# Generated by Django 3.1.2 on 2021-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='seat_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pending',
            name='seat_number',
            field=models.CharField(max_length=50),
        ),
    ]
