# Generated by Django 3.1.2 on 2021-09-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pending',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
