# Generated by Django 3.1.2 on 2021-10-14 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.TextField()),
                ('poster_image', models.ImageField(upload_to='thumbnails/')),
                ('summery', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.TextField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('entry_fee', models.IntegerField()),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('play_time', models.CharField(choices=[('8:30-AM', '8:30'), ('11:30-AM', '11:30'), ('2:30-PM', '14:30'), ('5:30-PM', '17:30'), ('8:30-PM', '20:30')], max_length=300)),
                ('status', models.CharField(choices=[('Empty', 'empty'), ('Filling', 'filling'), ('Housefull', 'housefull'), ('Cancelled', 'cancelled')], max_length=300)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='%y/%m/%d/images')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
