# Generated by Django 3.1.2 on 2021-10-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='staus',
            new_name='status',
        ),
    ]
