# Generated by Django 3.1.2 on 2021-09-26 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='play_time',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='screen_status',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='show_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_status', multiselectfield.db.fields.MultiSelectField(choices=[('empty', 'empty'), ('housefull', 'housefull'), ('filling', 'filling'), ('canceled', 'canceled')], max_length=32)),
                ('time', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
