# Generated by Django 3.1.2 on 2021-10-10 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('owner_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='%y/%m/%d/images')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
